language: node_js
node_js:
  - "8"
branches:
  only:
    - master
before_script:
  - npm install -g firebase-tools
script:
  - npm install
  - npm run build
  - cd functions && npm install && cd -
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN